### ISSUE TITLE
Question about BLEU scores/model training

### ISSUE THREAD

**Issue by vasily789** [takase/share_layer_params#3]
Hi,

I am trying to calculate SacreBLEU scores after the model stopped training with the issue with Floating Point Error around epoch 76 epoch (25.5 K updates) with valid PPL ~4.6:

| WARNING: overflow detected, setting loss scale to: 0.000244140625
| WARNING: overflow detected, setting loss scale to: 0.0001220703125
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.

Creating average checkpoint worked without any issues. However, the next step: Decoding with the averaged checkpoint
python generate.py pre-processed-data-dir --path model-save-dir/averaged.pt  --beam 4 --lenpen 0.6 --remove-bpe | grep '^H' | sed 's/^H\-//g' | sort -t ' ' -k1,1 -n | cut -f 3- > generated.result

the following error pops up:
Traceback (most recent call last):
  File "my_directory/share_layer_params-main/fairseq/checkpoint_utils.py", line 140, in load_checkpoint_to_cpu
    from fairseq.fb_pathmgr import fb_pathmgr
ModuleNotFoundError: No module named 'fairseq.fb_pathmgr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 201, in <module>
    cli_main()
  File "generate.py", line 197, in cli_main
    main(args)
  File "generate.py", line 47, in main
    task=task,
  File "my_directory/share_layer_params-main/fairseq/checkpoint_utils.py", line 167, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(filenames, arg_overrides, task)
  File "my_directory/share_layer_params-main/fairseq/checkpoint_utils.py", line 178, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "my_directory/share_layer_params-main/fairseq/checkpoint_utils.py", line 148, in load_checkpoint_to_cpu
    path, map_location=lambda s, l: default_restore_location(s, 'cpu'),
  File "my_directory/anaconda3/envs/WMT4/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "my_directory/anaconda3/envs/WMT4/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "my_directory/anaconda3/envs/WMT4/lib/python3.7/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'fairseq.logging'

I was able to solve this problem by switching to run the command from https://github.com/pytorch/fairseq/tree/main/examples/scaling_nmt

fairseq-generate \
    data-bin/wmt16_en_de_bpe32k \
    --path checkpoint.avg10.pt \
    --beam 4 --lenpen 0.6 --remove-bpe > gen.out

However, it runs into another issue with Missing and Unexpected key(s) in the state_dict:
RuntimeError: Error(s) in loading state_dict for TransformerModel:
     Missing key(s) in state_dict: "encoder.layers.0.self_attn_layer_norm.weight", ....
     Unexpected key(s) in state_dict: "encoder.layers.0.attention_ratio_change",...

I am not sure why keys are different. But this issue also arises when I am trying to restart the training from the checkpoint.

Next, I changed the load_state_dict() parameter strict from True to False line 1463 in /torch/nn/modules/module.py, and the issues with Missing/Unexpected key(s) of course disappeared and I was able to generate a generate.result file.

But in the final steps, I got a BLEU score of 0.00. 

The questions are:
1) Do I need to just train longer the whole training of 50K updates (changing grad-clip, batch size, etc.) and that's what causes the BLEU score to be 0.00? or
2) Does generated.result file seem to be wrong because I had to do stuff with fairseq-generate instead of generate.py file plus the extra issues with keys described above? or
3) Something else?

Appreciate your help and suggestions.

**Comment by takase** [comment]
1. If you want to obtain a superior model, you have to train the model until 50K updates. In my configuration, I don't use the fp16 option. If you use it, please try to remove it.
2. I think the generated results are wrong. Did you see the results? Are sequences fluent natural language? The following command might solve the issue: `pip install --editable .` or try to add fairseq directory to PYTHONPATH.

**Comment by vasily789** [comment]
Thank you for your reply.
1. Yes, I did use fp16, I will try to remove fp16 and run it again and let you know. 
2. The generated.result.detok file looks like (that's on that model that I mentioned in the above comment)
GGGGGGGGGGGGGGGGGGGGGGG...
MMMMMMMMMMMMMMMMMM...
MMMGMMMMMMMMMMMMMMM...
aufaufaufaufaufaufaufaufaufaufaufaufau...
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh...
DDDDDDDDDDDDDDDDDDDDDDDDDDD...
herfür für für für für für für für für für für 

I guess it's nothing like fluent natural language))

**Comment by takase** [comment]
I see.
Before re-training, I recommend trying to generate a desirable sequence.
If a generation succeeds, you can obtain a natural language sequence even if you use a model whose training is incomplete.

In my understanding, fb_pathmgr is necessary during training. Thus, I think you can conduct generate.py when your configuration is the same as in training.
Or, if you conduct `pip install --editable .`, you might be able to use fairseq-generate .
