### ISSUE TITLE
Can not exec on windows.

### ISSUE THREAD

**Issue by fkjslee** [takase/share_layer_params#4]
When I run "pip install --editable .". "sys/mman.h": No such file or directory will be given. 
Is this code can only be executed on linux?

**Comment by takase** [comment]
pip is a package-management system written in Python. https://en.wikipedia.org/wiki/Pip_(package_manager)
Please check whether you can run pip on your machine.

**Comment by fkjslee** [comment]
Thx for your reply, I fixed it out by install fairseq=1.10.0 which download from https://github.com/pytorch/fairseq
