### ISSUE TITLE
dear author, I want to know how much BLEU4 score should be got finally. 

### ISSUE THREAD

**Issue by fkjslee** [takase/share_layer_params#5]

**Comment by takase** [comment]
If you use WMT datasets, the scores are reported in [our paper](https://arxiv.org/abs/2104.06022).
If you want to know more details, I appreciate you explain more details for your configuration.

**Comment by fkjslee** [comment]
sry, I don't know why this draft be sent. I have write again in https://github.com/takase/share_layer_params/issues/6
