### ISSUE TITLE
Questions about computational speed

### ISSUE THREAD

**Issue by Juanrong** [takase/share_layer_params#7]
I have some questions about computational speed reported in the article. In my understanding, "We increased the dimensions of each layer for a fair comparison in terms of the number of parameters" , it means the parameter each layer should be increased if we use layer parameter sharing. Why the computational speed is faster even with the same layer? 
I have tried (1) vanilla transformer (2) universal transformer without increased dimension each layer (3) universal transformer with increased dimension each layer to keep same parameters as (1), it seems (3) is not faster than (1). Looking forward to your reply. Thanks!

**Comment by takase** [comment]
Hi, thank you for your interest in our paper, but I'm sorry I cannot understand your question.

In our paper, Table 1 shows that Universal Transformer whose parameter size is almost the same as one of Vanilla Transformer is much slower than Vanilla Transformer such as your observation.
In other words, we didn't claim that Universal Transformer is faster than Vanilla Transformer.

If I misunderstand your question, I appreciate explaining details of your question.

**Comment by Juanrong** [comment]
Here are some details about my question. My confusion is about Table1 actually.
![image](https://user-images.githubusercontent.com/45410660/150920933-37d91438-8467-4d26-ac25-ae5b10284058.png)
The speed of Vanilla is X1.00 and else are < X1.00 . Doesn't that mean < X1.00  is faster than X1.00? Or my understanding is wrong? Thank you.

**Comment by takase** [comment]
I see.

The column of Speed represents the computational speed based on tokens per second.
Thus, larger is faster.
Therefore, Table 1 indicates that Universal Transformer is (much) slower than Vanilla Transformer.

**Comment by Juanrong** [comment]
Got it. Thanks a lot.
