### ISSUE TITLE
About the training environment

### ISSUE THREAD

**Issue by bityigoss** [takase/share_layer_params#9]
Thanks for your work, can you provide a full list of requirements, e.g. requirements.txt

**Comment by takase** [comment]
In my understanding, the requirements is described in readme: PyTorch version == 1.4.0 and Python version >= 3.6.
If you could not run our code with the environment, we appreciate it if you tell us your situation.

**Comment by bityigoss** [comment]
@takase Thanks for you reply, actually I met some problem when try to training the model.
**my torch version is 1.4.0 and python is 3.7.12.** 
After I start the training script, I got a error and the training process exited. the log is as follows:
encoder attn ratio: 1.0
encoder ffn ratio: 1.3188899755477905
encoder attn ratio: 1.4434553384780884
encoder ffn ratio: 1.4966070652008057
encoder attn ratio: 1.613124132156372
encoder ffn ratio: 1.6823008060455322
encoder attn ratio: 1.786622405052185
encoder ffn ratio: 1.8575493097305298
encoder attn ratio: 1.9502540826797485
encoder ffn ratio: 2.022615671157837
encoder attn ratio: 2.1119792461395264
encoder ffn ratio: 2.181633949279785
decoder self attn ratio: 1.0
decoder encoder attn ratio: 1.3583709001541138
decoder ffn ratio: 1.4601109027862549
decoder self attn ratio: 1.5857242345809937
decoder encoder attn ratio: 1.6637381315231323
decoder ffn ratio: 1.7597150802612305
decoder self attn ratio: 1.8572213649749756
decoder encoder attn ratio: 1.9401099681854248
decoder ffn ratio: 2.0272738933563232
decoder self attn ratio: 2.122746467590332
decoder encoder attn ratio: 2.204719305038452
decoder ffn ratio: 2.281920909881592
decoder self attn ratio: 2.368241786956787
decoder encoder attn ratio: 2.4461982250213623
decoder ffn ratio: 2.5116090774536133
decoder self attn ratio: 2.5861854553222656
decoder encoder attn ratio: 2.6666133403778076
decoder ffn ratio: 2.719247817993164
None
Traceback (most recent call last):
  File "/attention/share_layer_params/fairseq/fairseq_cli/train.py", line 348, in <module>
    cli_main()
  File "/attention/share_layer_params/fairseq/fairseq_cli/train.py", line 340, in cli_main
    nprocs=args.distributed_world_size,
  File "//.conda/envs/mtexp/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/.conda/envs/mtexp/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 112, in join
    (error_index, exitcode)
Exception: process 0 terminated with exit code 1

**Comment by bityigoss** [comment]
@takase By the way, my torch version is 1.4.0 and python is 3.7.12. Thanks for you reply.

**Comment by bityigoss** [comment]
Hi, @takase.
I find if we remove **--init-type adaptive-profiling** option, there is no error occurs, do you know is there any problem with the option?

**Comment by takase** [comment]
Did you run the code on 1 GPU?
To use Admin, which makes the training of deep Transformers stable, we have to run profiling then training.
During the profiling (--init-type adaptive-profiling), we have to run the code on 1 GPU.
To train a model (--init-type adaptive), we can use multiple GPUs.
I hope this information solves your problem.

**Comment by bityigoss** [comment]
I see, thank you.
